import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import {back} from '../public/cards/BACK.png';
import Boton from '../componentes/Boton';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blackjack 3.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className='contenedor-principal'>
        
        <div className='tablero'>

          <div className="contenedor-titulo">
            <div className="grid"></div>
            <div className="lines"></div>
            <h1 className='h1-retro'>
              <span>BLACKJACK</span>
              <span>BLACKJACK</span>
            </h1>
            <h2 className='h2-retro'>3. 0</h2>

          </div>
          

          
          
          <div className="dealer-cards"> 
            <h2 className='h2-normal h2-dealer'>Dealer</h2>
            <img className='card' src='cards/BACK.png'></img>
          </div>
    
          
          <div className="your-cards">
            <h2 className='h2-normal h2-tu'>Tú:</h2>
          </div>
    
            
        </div>
        <div className='opciones'>
          <div className='robar opcion'>Robar</div>
          <div className='plantarse opcion'>Plantarse</div>
          <div className='rendirse opcion'>Rendirse</div>

        </div>
      </div>

    </div>
        
         
      
  )
}
